language: node_js
os: linux
sudo: required
services:
  - mongodb
before_install:
  - psql -c 'create database sms;' -U postgres
script:
  - npm test
  - npm run coveralls
node_js: "10"
cache:
  directories:
    - node_modules
install: npm install
